# Change these first
owner: DozKooki # Your GitHub organization or username, where this repository lives
repo: dozhost-status # The name of this repository

sites:
  - name: DozHost Panel
    url: https://dozhost.qzz.io
  - name: DozHost Status Page
    url: https://status.dozhost.qzz.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dozhost.qzz.io
  # baseUrl: /your-repo-name
  name: DozHost Status
  introTitle: "DozHost Service Status"
  introMessage: Live status of all DozHost services. Check here if you're experiencing any issues.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/DozKooki/dozhost-status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
